# Overrides for production environment
baseurl = "https://morozov-ext.github.io/SSG-docs/"
title = "Домашняя страница"

[caches]
  [caches.images]
    dir = ':cacheDir/static/images'

[permalinks]
blog = "./notes/:slug/"
docs = "./docs/:sections[1:]/:slug/"
