# Overrides for production environment
baseurl = "https://morozov-ext.github.io/SSG-docs/"
title = "Домашняя страница"

[caches]
  [caches.images]
    dir = ':cacheDir/static/images'

[permalinks]
blog = "SSG-docs/notes/:slug/"
docs = "SSG-docs/docs/:sections[1:]/:slug/"
